spring.application.name=todo-app

spring.datasource.url=jdbc:postgresql://localhost:5432/todo_app_db
spring.datasource.username=postgres
spring.datasource.password=ecuacion
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect